apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-controller
roleRef:
  apiGroup: ""
  kind: Role
  name: sample-controller
subjects:
- kind: ServiceAccount
  name: sample-controller
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-controller
      version: v1
  template:
    metadata:
      labels:
        app: sample-controller
        version: v1
    spec:
      serviceAccountName: sample-controller
      containers:
      - image: quay.io/jdamata/py-leader-election-sample-controller
        imagePullPolicy: Always
        name: sample-controller
        ports:
        - containerPort: 80
        env:
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
